# -*- coding: utf-8 -*-
"""Tugas Strategi Algoritma: Implementasi Backtracking pada N-Queens Problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13B06mZjNzcMCFTU_yrx0vqPiZ1Nk1ukc
"""

import time
from IPython.display import clear_output

# Fungsi untuk mengecek apakah posisi Ratu aman dari serangan Ratu lain
def is_safe(board, row, col, n):
    # Cek baris di sisi kiri
    for i in range(col):
        if board[row][i] == 1:
            return False

    # Cek diagonal atas kiri
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    # Cek diagonal bawah kiri
    for i, j in zip(range(row, n, 1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    return True

# Fungsi untuk menampilkan visualisasi papan catur di Google Colab
def print_board_colab(board, n, step_info=""):
    clear_output(wait=True)
    print(f"--- VISUALISASI BACKTRACKING N-QUEENS ---")
    print(f"Status: {step_info}")
    print("-----------------------------------------")
    for row in board:
        # Menampilkan 'Q' untuk Ratu dan '.' untuk kotak kosong
        print("  " + "  ".join("Q" if x == 1 else "." for x in row))
    print("-----------------------------------------")
    time.sleep(0.5) # Jeda 0.5 detik agar proses pencarian terlihat jelas

# Fungsi utama rekursif dengan algoritma Backtracking
def solve_n_queens(board, col, n):
    # Base case: Jika semua ratu sudah diletakkan
    if col >= n:
        return True

    for i in range(n):
        # Coba letakkan ratu di baris i, kolom col
        if is_safe(board, i, col, n):
            board[i][col] = 1
            print_board_colab(board, n, f"Mencoba Ratu di baris {i}, kolom {col}")

            # Rekursi untuk meletakkan ratu di kolom berikutnya
            if solve_n_queens(board, col + 1, n):
                return True

            # BACKTRACK: Jika tidak membawa ke solusi, hapus ratu dari posisi ini
            board[i][col] = 0
            print_board_colab(board, n, f"Backtrack: Baris {i}, kolom {col} buntu!")

    return False

# Konfigurasi Awal
N = 4  # Gunakan 4x4 agar visualisasi cepat dan mudah dipahami untuk demo
board = [[0 for _ in range(N)] for _ in range(N)]

# Eksekusi Program
if solve_n_queens(board, 0, N):
    print("\nSOLUSI AKHIR BERHASIL DITEMUKAN!")
else:
    print("\nSISTEM TIDAK MENEMUKAN SOLUSI.")